# Nom de l'application
spring.application.name=Projet_IRT31
  
  # Port du serveur (je l'ai ajouté pour vous)
server.port=8081
  
  # 1. Connexion Base de Données
  # ATTENTION : Vous avez changé le nom pour 'Post_emploi'.
  # Assurez-vous d'avoir créé cette base dans pgAdmin !
spring.datasource.url=jdbc:postgresql://localhost:5432/Post_emploi
spring.datasource.username=postgres
spring.datasource.password=1234
  
  # 2. Configuration JPA / Hibernate
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect